"""fix_deprecated_datetime_usage

Revision ID: 3ce4a4d49edb
Revises: 87c3e5f21a92
Create Date: 2025-07-28 09:24:11.888718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic
revision = '3ce4a4d49edb'
down_revision = '87c3e5f21a92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_deductible_expense_types_id'), 'deductible_expense_types', ['id'], unique=False)
    op.create_index(op.f('ix_income_sources_id'), 'income_sources', ['id'], unique=False)
    op.create_index(op.f('ix_medical_tax_credits_id'), 'medical_tax_credits', ['id'], unique=False)
    op.create_index(op.f('ix_tax_brackets_id'), 'tax_brackets', ['id'], unique=False)
    op.create_index(op.f('ix_tax_calculations_id'), 'tax_calculations', ['id'], unique=False)
    op.create_index(op.f('ix_tax_rebates_id'), 'tax_rebates', ['id'], unique=False)
    op.create_index(op.f('ix_tax_thresholds_id'), 'tax_thresholds', ['id'], unique=False)
    op.create_index(op.f('ix_user_expenses_id'), 'user_expenses', ['id'], unique=False)
    op.create_index(op.f('ix_user_profiles_id'), 'user_profiles', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_profiles_id'), table_name='user_profiles')
    op.drop_index(op.f('ix_user_expenses_id'), table_name='user_expenses')
    op.drop_index(op.f('ix_tax_thresholds_id'), table_name='tax_thresholds')
    op.drop_index(op.f('ix_tax_rebates_id'), table_name='tax_rebates')
    op.drop_index(op.f('ix_tax_calculations_id'), table_name='tax_calculations')
    op.drop_index(op.f('ix_tax_brackets_id'), table_name='tax_brackets')
    op.drop_index(op.f('ix_medical_tax_credits_id'), table_name='medical_tax_credits')
    op.drop_index(op.f('ix_income_sources_id'), table_name='income_sources')
    op.drop_index(op.f('ix_deductible_expense_types_id'), table_name='deductible_expense_types')
    # ### end Alembic commands ###
