"""add_is_admin_field_to_user_profile

Revision ID: 6bd21db2c3ed
Revises:
Create Date: 2025-05-08 14:37:14.712871

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic
revision = "6bd21db2c3ed"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    ###  # commands auto generated by Alembic - please adjust! ###
    pass
    ###  # end Alembic commands ###


def downgrade():
    ###  # commands auto generated by Alembic - please adjust! ###
    pass
    ###  # end Alembic commands ###
